/**
 * Generated from libphonenumber-js's country list — every region it can validate
 * a number for. Static rather than derived at runtime so the server and the
 * browser always render identical <option> lists.
 *
 * Regenerate with: node scripts/gen-countries.mjs
 */
export interface Country {
  /** ISO 3166-1 alpha-2. */
  iso: string;
  name: string;
  /** Demonym where one is in common use, otherwise the country name. */
  nationality: string;
  /** International dialling code, without the leading +. */
  dial: string;
  /** True for the main country on a shared dialling code (GB for +44). */
  primary: boolean;
}

export const COUNTRIES: Country[] = [
  { iso: 'AF', name: "Afghanistan", nationality: "Afghan", dial: '93', primary: true },
  { iso: 'AX', name: "Åland Islands", nationality: "Åland Islands", dial: '358', primary: false },
  { iso: 'AL', name: "Albania", nationality: "Albanian", dial: '355', primary: true },
  { iso: 'DZ', name: "Algeria", nationality: "Algerian", dial: '213', primary: true },
  { iso: 'AS', name: "American Samoa", nationality: "American Samoa", dial: '1', primary: false },
  { iso: 'AD', name: "Andorra", nationality: "Andorran", dial: '376', primary: true },
  { iso: 'AO', name: "Angola", nationality: "Angolan", dial: '244', primary: true },
  { iso: 'AI', name: "Anguilla", nationality: "Anguilla", dial: '1', primary: false },
  { iso: 'AG', name: "Antigua & Barbuda", nationality: "Antiguan or Barbudan", dial: '1', primary: false },
  { iso: 'AR', name: "Argentina", nationality: "Argentine", dial: '54', primary: true },
  { iso: 'AM', name: "Armenia", nationality: "Armenian", dial: '374', primary: true },
  { iso: 'AW', name: "Aruba", nationality: "Aruba", dial: '297', primary: true },
  { iso: 'AC', name: "Ascension Island", nationality: "Ascension Island", dial: '247', primary: true },
  { iso: 'AU', name: "Australia", nationality: "Australian", dial: '61', primary: true },
  { iso: 'AT', name: "Austria", nationality: "Austrian", dial: '43', primary: true },
  { iso: 'AZ', name: "Azerbaijan", nationality: "Azerbaijani", dial: '994', primary: true },
  { iso: 'BS', name: "Bahamas", nationality: "Bahamian", dial: '1', primary: false },
  { iso: 'BH', name: "Bahrain", nationality: "Bahraini", dial: '973', primary: true },
  { iso: 'BD', name: "Bangladesh", nationality: "Bangladeshi", dial: '880', primary: true },
  { iso: 'BB', name: "Barbados", nationality: "Barbadian", dial: '1', primary: false },
  { iso: 'BY', name: "Belarus", nationality: "Belarusian", dial: '375', primary: true },
  { iso: 'BE', name: "Belgium", nationality: "Belgian", dial: '32', primary: true },
  { iso: 'BZ', name: "Belize", nationality: "Belizean", dial: '501', primary: true },
  { iso: 'BJ', name: "Benin", nationality: "Beninese", dial: '229', primary: true },
  { iso: 'BM', name: "Bermuda", nationality: "Bermuda", dial: '1', primary: false },
  { iso: 'BT', name: "Bhutan", nationality: "Bhutanese", dial: '975', primary: true },
  { iso: 'BO', name: "Bolivia", nationality: "Bolivian", dial: '591', primary: true },
  { iso: 'BA', name: "Bosnia & Herzegovina", nationality: "Bosnian or Herzegovinian", dial: '387', primary: true },
  { iso: 'BW', name: "Botswana", nationality: "Botswanan", dial: '267', primary: true },
  { iso: 'BR', name: "Brazil", nationality: "Brazilian", dial: '55', primary: true },
  { iso: 'IO', name: "British Indian Ocean Territory", nationality: "British Indian Ocean Territory", dial: '246', primary: true },
  { iso: 'VG', name: "British Virgin Islands", nationality: "British Virgin Islands", dial: '1', primary: false },
  { iso: 'BN', name: "Brunei", nationality: "Bruneian", dial: '673', primary: true },
  { iso: 'BG', name: "Bulgaria", nationality: "Bulgarian", dial: '359', primary: true },
  { iso: 'BF', name: "Burkina Faso", nationality: "Burkinabé", dial: '226', primary: true },
  { iso: 'BI', name: "Burundi", nationality: "Burundian", dial: '257', primary: true },
  { iso: 'CV', name: "Cabo Verde", nationality: "Cabo Verdean", dial: '238', primary: true },
  { iso: 'KH', name: "Cambodia", nationality: "Cambodian", dial: '855', primary: true },
  { iso: 'CM', name: "Cameroon", nationality: "Cameroonian", dial: '237', primary: true },
  { iso: 'CA', name: "Canada", nationality: "Canadian", dial: '1', primary: false },
  { iso: 'BQ', name: "Caribbean Netherlands", nationality: "Caribbean Netherlands", dial: '599', primary: false },
  { iso: 'KY', name: "Cayman Islands", nationality: "Cayman Islands", dial: '1', primary: false },
  { iso: 'CF', name: "Central African Republic", nationality: "Central African", dial: '236', primary: true },
  { iso: 'TD', name: "Chad", nationality: "Chadian", dial: '235', primary: true },
  { iso: 'CL', name: "Chile", nationality: "Chilean", dial: '56', primary: true },
  { iso: 'CN', name: "China", nationality: "Chinese", dial: '86', primary: true },
  { iso: 'CX', name: "Christmas Island", nationality: "Christmas Island", dial: '61', primary: false },
  { iso: 'CC', name: "Cocos (Keeling) Islands", nationality: "Cocos (Keeling) Islands", dial: '61', primary: false },
  { iso: 'CO', name: "Colombia", nationality: "Colombian", dial: '57', primary: true },
  { iso: 'KM', name: "Comoros", nationality: "Comoran", dial: '269', primary: true },
  { iso: 'CD', name: "Congo (DR)", nationality: "Congolese (DR Congo)", dial: '243', primary: true },
  { iso: 'CG', name: "Congo (Republic)", nationality: "Congolese", dial: '242', primary: true },
  { iso: 'CK', name: "Cook Islands", nationality: "Cook Islands", dial: '682', primary: true },
  { iso: 'CR', name: "Costa Rica", nationality: "Costa Rican", dial: '506', primary: true },
  { iso: 'CI', name: "Côte d’Ivoire", nationality: "Ivorian", dial: '225', primary: true },
  { iso: 'HR', name: "Croatia", nationality: "Croatian", dial: '385', primary: true },
  { iso: 'CU', name: "Cuba", nationality: "Cuban", dial: '53', primary: true },
  { iso: 'CW', name: "Curaçao", nationality: "Curaçao", dial: '599', primary: true },
  { iso: 'CY', name: "Cyprus", nationality: "Cypriot", dial: '357', primary: true },
  { iso: 'CZ', name: "Czechia", nationality: "Czech", dial: '420', primary: true },
  { iso: 'DK', name: "Denmark", nationality: "Danish", dial: '45', primary: true },
  { iso: 'DJ', name: "Djibouti", nationality: "Djiboutian", dial: '253', primary: true },
  { iso: 'DM', name: "Dominica", nationality: "Dominican (Dominica)", dial: '1', primary: false },
  { iso: 'DO', name: "Dominican Republic", nationality: "Dominican (Dominican Republic)", dial: '1', primary: false },
  { iso: 'EC', name: "Ecuador", nationality: "Ecuadorian", dial: '593', primary: true },
  { iso: 'EG', name: "Egypt", nationality: "Egyptian", dial: '20', primary: true },
  { iso: 'SV', name: "El Salvador", nationality: "Salvadoran", dial: '503', primary: true },
  { iso: 'GQ', name: "Equatorial Guinea", nationality: "Equatorial Guinean", dial: '240', primary: true },
  { iso: 'ER', name: "Eritrea", nationality: "Eritrean", dial: '291', primary: true },
  { iso: 'EE', name: "Estonia", nationality: "Estonian", dial: '372', primary: true },
  { iso: 'SZ', name: "Eswatini", nationality: "Swazi", dial: '268', primary: true },
  { iso: 'ET', name: "Ethiopia", nationality: "Ethiopian", dial: '251', primary: true },
  { iso: 'FK', name: "Falkland Islands", nationality: "Falkland Islands", dial: '500', primary: true },
  { iso: 'FO', name: "Faroe Islands", nationality: "Faroe Islands", dial: '298', primary: true },
  { iso: 'FJ', name: "Fiji", nationality: "Fijian", dial: '679', primary: true },
  { iso: 'FI', name: "Finland", nationality: "Finnish", dial: '358', primary: true },
  { iso: 'FR', name: "France", nationality: "French", dial: '33', primary: true },
  { iso: 'GF', name: "French Guiana", nationality: "French Guiana", dial: '594', primary: true },
  { iso: 'PF', name: "French Polynesia", nationality: "French Polynesia", dial: '689', primary: true },
  { iso: 'GA', name: "Gabon", nationality: "Gabonese", dial: '241', primary: true },
  { iso: 'GM', name: "Gambia", nationality: "Gambian", dial: '220', primary: true },
  { iso: 'GE', name: "Georgia", nationality: "Georgian", dial: '995', primary: true },
  { iso: 'DE', name: "Germany", nationality: "German", dial: '49', primary: true },
  { iso: 'GH', name: "Ghana", nationality: "Ghanaian", dial: '233', primary: true },
  { iso: 'GI', name: "Gibraltar", nationality: "Gibraltar", dial: '350', primary: true },
  { iso: 'GR', name: "Greece", nationality: "Greek", dial: '30', primary: true },
  { iso: 'GL', name: "Greenland", nationality: "Greenland", dial: '299', primary: true },
  { iso: 'GD', name: "Grenada", nationality: "Grenadian", dial: '1', primary: false },
  { iso: 'GP', name: "Guadeloupe", nationality: "Guadeloupe", dial: '590', primary: true },
  { iso: 'GU', name: "Guam", nationality: "Guam", dial: '1', primary: false },
  { iso: 'GT', name: "Guatemala", nationality: "Guatemalan", dial: '502', primary: true },
  { iso: 'GG', name: "Guernsey", nationality: "Guernsey", dial: '44', primary: false },
  { iso: 'GN', name: "Guinea", nationality: "Guinean", dial: '224', primary: true },
  { iso: 'GW', name: "Guinea-Bissau", nationality: "Bissau-Guinean", dial: '245', primary: true },
  { iso: 'GY', name: "Guyana", nationality: "Guyanese", dial: '592', primary: true },
  { iso: 'HT', name: "Haiti", nationality: "Haitian", dial: '509', primary: true },
  { iso: 'HN', name: "Honduras", nationality: "Honduran", dial: '504', primary: true },
  { iso: 'HK', name: "Hong Kong SAR China", nationality: "Hong Kong SAR China", dial: '852', primary: true },
  { iso: 'HU', name: "Hungary", nationality: "Hungarian", dial: '36', primary: true },
  { iso: 'IS', name: "Iceland", nationality: "Icelandic", dial: '354', primary: true },
  { iso: 'IN', name: "India", nationality: "Indian", dial: '91', primary: true },
  { iso: 'ID', name: "Indonesia", nationality: "Indonesian", dial: '62', primary: true },
  { iso: 'IR', name: "Iran", nationality: "Iranian", dial: '98', primary: true },
  { iso: 'IQ', name: "Iraq", nationality: "Iraqi", dial: '964', primary: true },
  { iso: 'IE', name: "Ireland", nationality: "Irish", dial: '353', primary: true },
  { iso: 'IM', name: "Isle of Man", nationality: "Isle of Man", dial: '44', primary: false },
  { iso: 'IL', name: "Israel", nationality: "Israeli", dial: '972', primary: true },
  { iso: 'IT', name: "Italy", nationality: "Italian", dial: '39', primary: true },
  { iso: 'JM', name: "Jamaica", nationality: "Jamaican", dial: '1', primary: false },
  { iso: 'JP', name: "Japan", nationality: "Japanese", dial: '81', primary: true },
  { iso: 'JE', name: "Jersey", nationality: "Jersey", dial: '44', primary: false },
  { iso: 'JO', name: "Jordan", nationality: "Jordanian", dial: '962', primary: true },
  { iso: 'KZ', name: "Kazakhstan", nationality: "Kazakhstani", dial: '7', primary: false },
  { iso: 'KE', name: "Kenya", nationality: "Kenyan", dial: '254', primary: true },
  { iso: 'KI', name: "Kiribati", nationality: "I-Kiribati", dial: '686', primary: true },
  { iso: 'XK', name: "Kosovo", nationality: "Kosovar", dial: '383', primary: true },
  { iso: 'KW', name: "Kuwait", nationality: "Kuwaiti", dial: '965', primary: true },
  { iso: 'KG', name: "Kyrgyzstan", nationality: "Kyrgyz", dial: '996', primary: true },
  { iso: 'LA', name: "Laos", nationality: "Lao", dial: '856', primary: true },
  { iso: 'LV', name: "Latvia", nationality: "Latvian", dial: '371', primary: true },
  { iso: 'LB', name: "Lebanon", nationality: "Lebanese", dial: '961', primary: true },
  { iso: 'LS', name: "Lesotho", nationality: "Basotho", dial: '266', primary: true },
  { iso: 'LR', name: "Liberia", nationality: "Liberian", dial: '231', primary: true },
  { iso: 'LY', name: "Libya", nationality: "Libyan", dial: '218', primary: true },
  { iso: 'LI', name: "Liechtenstein", nationality: "Liechtensteiner", dial: '423', primary: true },
  { iso: 'LT', name: "Lithuania", nationality: "Lithuanian", dial: '370', primary: true },
  { iso: 'LU', name: "Luxembourg", nationality: "Luxembourgish", dial: '352', primary: true },
  { iso: 'MO', name: "Macao SAR China", nationality: "Macao SAR China", dial: '853', primary: true },
  { iso: 'MG', name: "Madagascar", nationality: "Malagasy", dial: '261', primary: true },
  { iso: 'MW', name: "Malawi", nationality: "Malawian", dial: '265', primary: true },
  { iso: 'MY', name: "Malaysia", nationality: "Malaysian", dial: '60', primary: true },
  { iso: 'MV', name: "Maldives", nationality: "Maldivian", dial: '960', primary: true },
  { iso: 'ML', name: "Mali", nationality: "Malian", dial: '223', primary: true },
  { iso: 'MT', name: "Malta", nationality: "Maltese", dial: '356', primary: true },
  { iso: 'MH', name: "Marshall Islands", nationality: "Marshallese", dial: '692', primary: true },
  { iso: 'MQ', name: "Martinique", nationality: "Martinique", dial: '596', primary: true },
  { iso: 'MR', name: "Mauritania", nationality: "Mauritanian", dial: '222', primary: true },
  { iso: 'MU', name: "Mauritius", nationality: "Mauritian", dial: '230', primary: true },
  { iso: 'YT', name: "Mayotte", nationality: "Mayotte", dial: '262', primary: false },
  { iso: 'MX', name: "Mexico", nationality: "Mexican", dial: '52', primary: true },
  { iso: 'FM', name: "Micronesia", nationality: "Micronesian", dial: '691', primary: true },
  { iso: 'MD', name: "Moldova", nationality: "Moldovan", dial: '373', primary: true },
  { iso: 'MC', name: "Monaco", nationality: "Monégasque", dial: '377', primary: true },
  { iso: 'MN', name: "Mongolia", nationality: "Mongolian", dial: '976', primary: true },
  { iso: 'ME', name: "Montenegro", nationality: "Montenegrin", dial: '382', primary: true },
  { iso: 'MS', name: "Montserrat", nationality: "Montserrat", dial: '1', primary: false },
  { iso: 'MA', name: "Morocco", nationality: "Moroccan", dial: '212', primary: true },
  { iso: 'MZ', name: "Mozambique", nationality: "Mozambican", dial: '258', primary: true },
  { iso: 'MM', name: "Myanmar", nationality: "Burmese", dial: '95', primary: true },
  { iso: 'NA', name: "Namibia", nationality: "Namibian", dial: '264', primary: true },
  { iso: 'NR', name: "Nauru", nationality: "Nauruan", dial: '674', primary: true },
  { iso: 'NP', name: "Nepal", nationality: "Nepali", dial: '977', primary: true },
  { iso: 'NL', name: "Netherlands", nationality: "Dutch", dial: '31', primary: true },
  { iso: 'NC', name: "New Caledonia", nationality: "New Caledonia", dial: '687', primary: true },
  { iso: 'NZ', name: "New Zealand", nationality: "New Zealander", dial: '64', primary: true },
  { iso: 'NI', name: "Nicaragua", nationality: "Nicaraguan", dial: '505', primary: true },
  { iso: 'NE', name: "Niger", nationality: "Nigerien", dial: '227', primary: true },
  { iso: 'NG', name: "Nigeria", nationality: "Nigerian", dial: '234', primary: true },
  { iso: 'NU', name: "Niue", nationality: "Niue", dial: '683', primary: true },
  { iso: 'NF', name: "Norfolk Island", nationality: "Norfolk Island", dial: '672', primary: true },
  { iso: 'KP', name: "North Korea", nationality: "North Korean", dial: '850', primary: true },
  { iso: 'MK', name: "North Macedonia", nationality: "Macedonian", dial: '389', primary: true },
  { iso: 'MP', name: "Northern Mariana Islands", nationality: "Northern Mariana Islands", dial: '1', primary: false },
  { iso: 'NO', name: "Norway", nationality: "Norwegian", dial: '47', primary: true },
  { iso: 'OM', name: "Oman", nationality: "Omani", dial: '968', primary: true },
  { iso: 'PK', name: "Pakistan", nationality: "Pakistani", dial: '92', primary: true },
  { iso: 'PW', name: "Palau", nationality: "Palauan", dial: '680', primary: true },
  { iso: 'PS', name: "Palestine", nationality: "Palestinian", dial: '970', primary: true },
  { iso: 'PA', name: "Panama", nationality: "Panamanian", dial: '507', primary: true },
  { iso: 'PG', name: "Papua New Guinea", nationality: "Papua New Guinean", dial: '675', primary: true },
  { iso: 'PY', name: "Paraguay", nationality: "Paraguayan", dial: '595', primary: true },
  { iso: 'PE', name: "Peru", nationality: "Peruvian", dial: '51', primary: true },
  { iso: 'PH', name: "Philippines", nationality: "Filipino", dial: '63', primary: true },
  { iso: 'PL', name: "Poland", nationality: "Polish", dial: '48', primary: true },
  { iso: 'PT', name: "Portugal", nationality: "Portuguese", dial: '351', primary: true },
  { iso: 'PR', name: "Puerto Rico", nationality: "Puerto Rico", dial: '1', primary: false },
  { iso: 'QA', name: "Qatar", nationality: "Qatari", dial: '974', primary: true },
  { iso: 'RE', name: "Réunion", nationality: "Réunion", dial: '262', primary: true },
  { iso: 'RO', name: "Romania", nationality: "Romanian", dial: '40', primary: true },
  { iso: 'RU', name: "Russia", nationality: "Russian", dial: '7', primary: true },
  { iso: 'RW', name: "Rwanda", nationality: "Rwandan", dial: '250', primary: true },
  { iso: 'WS', name: "Samoa", nationality: "Samoan", dial: '685', primary: true },
  { iso: 'SM', name: "San Marino", nationality: "Sammarinese", dial: '378', primary: true },
  { iso: 'ST', name: "São Tomé & Príncipe", nationality: "São Toméan", dial: '239', primary: true },
  { iso: 'SA', name: "Saudi Arabia", nationality: "Saudi Arabian", dial: '966', primary: true },
  { iso: 'SN', name: "Senegal", nationality: "Senegalese", dial: '221', primary: true },
  { iso: 'RS', name: "Serbia", nationality: "Serbian", dial: '381', primary: true },
  { iso: 'SC', name: "Seychelles", nationality: "Seychellois", dial: '248', primary: true },
  { iso: 'SL', name: "Sierra Leone", nationality: "Sierra Leonean", dial: '232', primary: true },
  { iso: 'SG', name: "Singapore", nationality: "Singaporean", dial: '65', primary: true },
  { iso: 'SX', name: "Sint Maarten", nationality: "Sint Maarten", dial: '1', primary: false },
  { iso: 'SK', name: "Slovakia", nationality: "Slovak", dial: '421', primary: true },
  { iso: 'SI', name: "Slovenia", nationality: "Slovenian", dial: '386', primary: true },
  { iso: 'SB', name: "Solomon Islands", nationality: "Solomon Islander", dial: '677', primary: true },
  { iso: 'SO', name: "Somalia", nationality: "Somali", dial: '252', primary: true },
  { iso: 'ZA', name: "South Africa", nationality: "South African", dial: '27', primary: true },
  { iso: 'KR', name: "South Korea", nationality: "South Korean", dial: '82', primary: true },
  { iso: 'SS', name: "South Sudan", nationality: "South Sudanese", dial: '211', primary: true },
  { iso: 'ES', name: "Spain", nationality: "Spanish", dial: '34', primary: true },
  { iso: 'LK', name: "Sri Lanka", nationality: "Sri Lankan", dial: '94', primary: true },
  { iso: 'BL', name: "St. Barthélemy", nationality: "St. Barthélemy", dial: '590', primary: false },
  { iso: 'SH', name: "St. Helena", nationality: "St. Helena", dial: '290', primary: true },
  { iso: 'KN', name: "St. Kitts & Nevis", nationality: "Kittitian or Nevisian", dial: '1', primary: false },
  { iso: 'LC', name: "St. Lucia", nationality: "Saint Lucian", dial: '1', primary: false },
  { iso: 'MF', name: "St. Martin", nationality: "St. Martin", dial: '590', primary: false },
  { iso: 'PM', name: "St. Pierre & Miquelon", nationality: "St. Pierre & Miquelon", dial: '508', primary: true },
  { iso: 'VC', name: "St. Vincent & Grenadines", nationality: "Vincentian", dial: '1', primary: false },
  { iso: 'SD', name: "Sudan", nationality: "Sudanese", dial: '249', primary: true },
  { iso: 'SR', name: "Suriname", nationality: "Surinamese", dial: '597', primary: true },
  { iso: 'SJ', name: "Svalbard & Jan Mayen", nationality: "Svalbard & Jan Mayen", dial: '47', primary: false },
  { iso: 'SE', name: "Sweden", nationality: "Swedish", dial: '46', primary: true },
  { iso: 'CH', name: "Switzerland", nationality: "Swiss", dial: '41', primary: true },
  { iso: 'SY', name: "Syria", nationality: "Syrian", dial: '963', primary: true },
  { iso: 'TW', name: "Taiwan", nationality: "Taiwanese", dial: '886', primary: true },
  { iso: 'TJ', name: "Tajikistan", nationality: "Tajik", dial: '992', primary: true },
  { iso: 'TZ', name: "Tanzania", nationality: "Tanzanian", dial: '255', primary: true },
  { iso: 'TH', name: "Thailand", nationality: "Thai", dial: '66', primary: true },
  { iso: 'TL', name: "Timor-Leste", nationality: "Timorese", dial: '670', primary: true },
  { iso: 'TG', name: "Togo", nationality: "Togolese", dial: '228', primary: true },
  { iso: 'TK', name: "Tokelau", nationality: "Tokelau", dial: '690', primary: true },
  { iso: 'TO', name: "Tonga", nationality: "Tongan", dial: '676', primary: true },
  { iso: 'TT', name: "Trinidad & Tobago", nationality: "Trinidadian or Tobagonian", dial: '1', primary: false },
  { iso: 'TA', name: "Tristan da Cunha", nationality: "Tristan da Cunha", dial: '290', primary: false },
  { iso: 'TN', name: "Tunisia", nationality: "Tunisian", dial: '216', primary: true },
  { iso: 'TR', name: "Türkiye", nationality: "Turkish", dial: '90', primary: true },
  { iso: 'TM', name: "Turkmenistan", nationality: "Turkmen", dial: '993', primary: true },
  { iso: 'TC', name: "Turks & Caicos Islands", nationality: "Turks & Caicos Islands", dial: '1', primary: false },
  { iso: 'TV', name: "Tuvalu", nationality: "Tuvaluan", dial: '688', primary: true },
  { iso: 'VI', name: "U.S. Virgin Islands", nationality: "U.S. Virgin Islands", dial: '1', primary: false },
  { iso: 'UG', name: "Uganda", nationality: "Ugandan", dial: '256', primary: true },
  { iso: 'UA', name: "Ukraine", nationality: "Ukrainian", dial: '380', primary: true },
  { iso: 'AE', name: "United Arab Emirates", nationality: "Emirati", dial: '971', primary: true },
  { iso: 'GB', name: "United Kingdom", nationality: "British", dial: '44', primary: true },
  { iso: 'US', name: "United States", nationality: "American", dial: '1', primary: true },
  { iso: 'UY', name: "Uruguay", nationality: "Uruguayan", dial: '598', primary: true },
  { iso: 'UZ', name: "Uzbekistan", nationality: "Uzbek", dial: '998', primary: true },
  { iso: 'VU', name: "Vanuatu", nationality: "Ni-Vanuatu", dial: '678', primary: true },
  { iso: 'VA', name: "Vatican City", nationality: "Vatican", dial: '39', primary: false },
  { iso: 'VE', name: "Venezuela", nationality: "Venezuelan", dial: '58', primary: true },
  { iso: 'VN', name: "Vietnam", nationality: "Vietnamese", dial: '84', primary: true },
  { iso: 'WF', name: "Wallis & Futuna", nationality: "Wallis & Futuna", dial: '681', primary: true },
  { iso: 'EH', name: "Western Sahara", nationality: "Western Sahara", dial: '212', primary: false },
  { iso: 'YE', name: "Yemen", nationality: "Yemeni", dial: '967', primary: true },
  { iso: 'ZM', name: "Zambia", nationality: "Zambian", dial: '260', primary: true },
  { iso: 'ZW', name: "Zimbabwe", nationality: "Zimbabwean", dial: '263', primary: true },
];

export const COUNTRY_BY_ISO: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((country) => [country.iso, country]),
);

/** Turns 'TH' into 🇹🇭 using regional indicator symbols. */
export function flagEmoji(iso: string): string {
  if (!/^[A-Z]{2}$/.test(iso)) return '';
  return String.fromCodePoint(...[...iso].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

export function countryName(iso: string): string {
  return COUNTRY_BY_ISO[iso]?.name ?? iso;
}

export function dialCode(iso: string): string {
  const country = COUNTRY_BY_ISO[iso];
  return country ? `+${country.dial}` : '';
}

/** Default for the phone picker — this is a Thai clinic product. */
export const DEFAULT_PHONE_COUNTRY = 'TH';
